title: "Albert Li"
author: "Albert Li"
description: "IPMB, Heidelberg University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "aboutMe.pdf", title: "About me"}
  - {file: "README.md", title: "Publication"}
  - {file: "CV.pdf", title: "CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:albert0325162@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/albert0325"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/AlbertL91063895"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
